// Generated by rstantools.  Do not edit by hand.

/*
    baysc is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    baysc is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with baysc.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_SWOLCA_main_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 97> locations_array__ =
  {" (found before start of program)",
  " (in 'SWOLCA_main', line 19, column 2 to column 16)",
  " (in 'SWOLCA_main', line 20, column 2 to column 25)",
  " (in 'SWOLCA_main', line 21, column 2 to column 18)",
  " (in 'SWOLCA_main', line 24, column 2 to column 26)",
  " (in 'SWOLCA_main', line 25, column 2 to column 20)",
  " (in 'SWOLCA_main', line 71, column 2 to column 33)",
  " (in 'SWOLCA_main', line 72, column 2 to column 29)",
  " (in 'SWOLCA_main', line 73, column 2 to column 26)",
  " (in 'SWOLCA_main', line 28, column 6 to column 44)",
  " (in 'SWOLCA_main', line 27, column 19 to line 29, column 5)",
  " (in 'SWOLCA_main', line 27, column 4 to line 29, column 5)",
  " (in 'SWOLCA_main', line 26, column 17 to line 30, column 3)",
  " (in 'SWOLCA_main', line 26, column 2 to line 30, column 3)",
  " (in 'SWOLCA_main', line 32, column 4 to column 31)",
  " (in 'SWOLCA_main', line 31, column 17 to line 33, column 3)",
  " (in 'SWOLCA_main', line 31, column 2 to line 33, column 3)",
  " (in 'SWOLCA_main', line 78, column 6 to column 96)",
  " (in 'SWOLCA_main', line 80, column 8 to column 87)",
  " (in 'SWOLCA_main', line 79, column 21 to line 81, column 7)",
  " (in 'SWOLCA_main', line 79, column 6 to line 81, column 7)",
  " (in 'SWOLCA_main', line 76, column 19 to line 83, column 5)",
  " (in 'SWOLCA_main', line 76, column 4 to line 83, column 5)",
  " (in 'SWOLCA_main', line 84, column 4 to column 78)",
  " (in 'SWOLCA_main', line 87, column 4 to column 59)",
  " (in 'SWOLCA_main', line 75, column 17 to line 88, column 3)",
  " (in 'SWOLCA_main', line 75, column 2 to line 88, column 3)",
  " (in 'SWOLCA_main', line 36, column 23 to column 24)",
  " (in 'SWOLCA_main', line 36, column 9 to column 10)",
  " (in 'SWOLCA_main', line 36, column 2 to column 26)",
  " (in 'SWOLCA_main', line 38, column 9 to column 10)",
  " (in 'SWOLCA_main', line 38, column 2 to column 18)",
  " (in 'SWOLCA_main', line 40, column 2 to column 24)",
  " (in 'SWOLCA_main', line 43, column 6 to column 40)",
  " (in 'SWOLCA_main', line 42, column 19 to line 44, column 5)",
  " (in 'SWOLCA_main', line 42, column 4 to line 44, column 5)",
  " (in 'SWOLCA_main', line 41, column 17 to line 45, column 3)",
  " (in 'SWOLCA_main', line 41, column 2 to line 45, column 3)",
  " (in 'SWOLCA_main', line 47, column 4 to column 42)",
  " (in 'SWOLCA_main', line 46, column 17 to line 48, column 3)",
  " (in 'SWOLCA_main', line 46, column 2 to line 48, column 3)",
  " (in 'SWOLCA_main', line 54, column 6 to column 47)",
  " (in 'SWOLCA_main', line 56, column 8 to column 22)",
  " (in 'SWOLCA_main', line 55, column 25 to line 57, column 7)",
  " (in 'SWOLCA_main', line 55, column 6 to line 57, column 7)",
  " (in 'SWOLCA_main', line 59, column 8 to column 21)",
  " (in 'SWOLCA_main', line 58, column 24 to line 60, column 7)",
  " (in 'SWOLCA_main', line 58, column 6 to line 60, column 7)",
  " (in 'SWOLCA_main', line 61, column 6 to column 75)",
  " (in 'SWOLCA_main', line 63, column 8 to column 87)",
  " (in 'SWOLCA_main', line 62, column 21 to line 64, column 7)",
  " (in 'SWOLCA_main', line 62, column 6 to line 64, column 7)",
  " (in 'SWOLCA_main', line 51, column 19 to line 65, column 5)",
  " (in 'SWOLCA_main', line 51, column 4 to line 65, column 5)",
  " (in 'SWOLCA_main', line 67, column 4 to column 54)",
  " (in 'SWOLCA_main', line 50, column 17 to line 68, column 3)",
  " (in 'SWOLCA_main', line 50, column 2 to line 68, column 3)",
  " (in 'SWOLCA_main', line 2, column 2 to column 17)",
  " (in 'SWOLCA_main', line 3, column 2 to column 17)",
  " (in 'SWOLCA_main', line 4, column 2 to column 17)",
  " (in 'SWOLCA_main', line 5, column 2 to column 17)",
  " (in 'SWOLCA_main', line 6, column 2 to column 17)",
  " (in 'SWOLCA_main', line 8, column 8 to column 9)",
  " (in 'SWOLCA_main', line 8, column 11 to column 12)",
  " (in 'SWOLCA_main', line 8, column 2 to column 14)",
  " (in 'SWOLCA_main', line 9, column 26 to column 27)",
  " (in 'SWOLCA_main', line 9, column 2 to column 29)",
  " (in 'SWOLCA_main', line 10, column 9 to column 10)",
  " (in 'SWOLCA_main', line 10, column 12 to column 13)",
  " (in 'SWOLCA_main', line 10, column 2 to column 15)",
  " (in 'SWOLCA_main', line 11, column 18 to column 19)",
  " (in 'SWOLCA_main', line 11, column 2 to column 29)",
  " (in 'SWOLCA_main', line 13, column 9 to column 10)",
  " (in 'SWOLCA_main', line 13, column 2 to column 18)",
  " (in 'SWOLCA_main', line 14, column 9 to column 10)",
  " (in 'SWOLCA_main', line 14, column 12 to column 13)",
  " (in 'SWOLCA_main', line 14, column 2 to column 19)",
  " (in 'SWOLCA_main', line 15, column 16 to column 17)",
  " (in 'SWOLCA_main', line 15, column 9 to column 10)",
  " (in 'SWOLCA_main', line 15, column 2 to column 19)",
  " (in 'SWOLCA_main', line 16, column 21 to column 22)",
  " (in 'SWOLCA_main', line 16, column 13 to column 14)",
  " (in 'SWOLCA_main', line 16, column 2 to column 24)",
  " (in 'SWOLCA_main', line 19, column 10 to column 11)",
  " (in 'SWOLCA_main', line 20, column 19 to column 20)",
  " (in 'SWOLCA_main', line 20, column 22 to column 23)",
  " (in 'SWOLCA_main', line 20, column 10 to column 11)",
  " (in 'SWOLCA_main', line 21, column 15 to column 16)",
  " (in 'SWOLCA_main', line 21, column 9 to column 10)",
  " (in 'SWOLCA_main', line 24, column 9 to column 10)",
  " (in 'SWOLCA_main', line 24, column 12 to column 13)",
  " (in 'SWOLCA_main', line 25, column 9 to column 10)",
  " (in 'SWOLCA_main', line 71, column 30 to column 31)",
  " (in 'SWOLCA_main', line 71, column 10 to column 11)",
  " (in 'SWOLCA_main', line 72, column 26 to column 27)",
  " (in 'SWOLCA_main', line 73, column 23 to column 24)",
  " (in 'SWOLCA_main', line 73, column 9 to column 10)"};
#include <stan_meta_header.hpp>
class model_SWOLCA_main final : public model_base_crtp<model_SWOLCA_main> {
private:
  int K;
  int J;
  int R;
  int n;
  int q;
  std::vector<std::vector<int>> X;
  std::vector<int> y;
  std::vector<std::vector<double>> V;
  Eigen::Matrix<double,-1,1> weights_data__;
  Eigen::Matrix<double,-1,1> alpha_data__;
  Eigen::Matrix<double,-1,-1> eta_data__;
  std::vector<Eigen::Matrix<double,-1,1>> mu0;
  std::vector<Eigen::Matrix<double,-1,-1>> Sig0;
  Eigen::Map<Eigen::Matrix<double,-1,1>> weights{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> alpha{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> eta{nullptr, 0, 0};
public:
  ~model_SWOLCA_main() {}
  model_SWOLCA_main(stan::io::var_context& context__, unsigned int
                    random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_SWOLCA_main_namespace::model_SWOLCA_main";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 57;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 57;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 57;
      stan::math::check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 58;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 58;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 58;
      stan::math::check_greater_or_equal(function__, "J", J, 1);
      current_statement__ = 59;
      context__.validate_dims("data initialization", "R", "int",
        std::vector<size_t>{});
      R = std::numeric_limits<int>::min();
      current_statement__ = 59;
      R = context__.vals_i("R")[(1 - 1)];
      current_statement__ = 59;
      stan::math::check_greater_or_equal(function__, "R", R, 1);
      current_statement__ = 60;
      context__.validate_dims("data initialization", "n", "int",
        std::vector<size_t>{});
      n = std::numeric_limits<int>::min();
      current_statement__ = 60;
      n = context__.vals_i("n")[(1 - 1)];
      current_statement__ = 60;
      stan::math::check_greater_or_equal(function__, "n", n, 1);
      current_statement__ = 61;
      context__.validate_dims("data initialization", "q", "int",
        std::vector<size_t>{});
      q = std::numeric_limits<int>::min();
      current_statement__ = 61;
      q = context__.vals_i("q")[(1 - 1)];
      current_statement__ = 61;
      stan::math::check_greater_or_equal(function__, "q", q, 1);
      current_statement__ = 62;
      stan::math::validate_non_negative_index("X", "n", n);
      current_statement__ = 63;
      stan::math::validate_non_negative_index("X", "J", J);
      current_statement__ = 64;
      context__.validate_dims("data initialization", "X", "int",
        std::vector<size_t>{static_cast<size_t>(n), static_cast<size_t>(J)});
      X = std::vector<std::vector<int>>(n,
            std::vector<int>(J, std::numeric_limits<int>::min()));
      {
        std::vector<int> X_flat__;
        current_statement__ = 64;
        X_flat__ = context__.vals_i("X");
        current_statement__ = 64;
        pos__ = 1;
        current_statement__ = 64;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 64;
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            current_statement__ = 64;
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 64;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 65;
      stan::math::validate_non_negative_index("y", "n", n);
      current_statement__ = 66;
      context__.validate_dims("data initialization", "y", "int",
        std::vector<size_t>{static_cast<size_t>(n)});
      y = std::vector<int>(n, std::numeric_limits<int>::min());
      current_statement__ = 66;
      y = context__.vals_i("y");
      current_statement__ = 66;
      stan::math::check_greater_or_equal(function__, "y", y, 0);
      current_statement__ = 66;
      stan::math::check_less_or_equal(function__, "y", y, 1);
      current_statement__ = 67;
      stan::math::validate_non_negative_index("V", "n", n);
      current_statement__ = 68;
      stan::math::validate_non_negative_index("V", "q", q);
      current_statement__ = 69;
      context__.validate_dims("data initialization", "V", "double",
        std::vector<size_t>{static_cast<size_t>(n), static_cast<size_t>(q)});
      V = std::vector<std::vector<double>>(n,
            std::vector<double>(q, std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> V_flat__;
        current_statement__ = 69;
        V_flat__ = context__.vals_r("V");
        current_statement__ = 69;
        pos__ = 1;
        current_statement__ = 69;
        for (int sym1__ = 1; sym1__ <= q; ++sym1__) {
          current_statement__ = 69;
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            current_statement__ = 69;
            stan::model::assign(V, V_flat__[(pos__ - 1)],
              "assigning variable V", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 69;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 70;
      stan::math::validate_non_negative_index("weights", "n", n);
      current_statement__ = 71;
      context__.validate_dims("data initialization", "weights", "double",
        std::vector<size_t>{static_cast<size_t>(n)});
      weights_data__ = Eigen::Matrix<double,-1,1>::Constant(n,
                         std::numeric_limits<double>::quiet_NaN());
      new (&weights)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(weights_data__.data(), n);
      {
        std::vector<local_scalar_t__> weights_flat__;
        current_statement__ = 71;
        weights_flat__ = context__.vals_r("weights");
        current_statement__ = 71;
        pos__ = 1;
        current_statement__ = 71;
        for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
          current_statement__ = 71;
          stan::model::assign(weights, weights_flat__[(pos__ - 1)],
            "assigning variable weights", stan::model::index_uni(sym1__));
          current_statement__ = 71;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 71;
      stan::math::check_greater_or_equal(function__, "weights", weights, 0);
      current_statement__ = 72;
      stan::math::validate_non_negative_index("alpha", "K", K);
      current_statement__ = 73;
      context__.validate_dims("data initialization", "alpha", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      alpha_data__ = Eigen::Matrix<double,-1,1>::Constant(K,
                       std::numeric_limits<double>::quiet_NaN());
      new (&alpha)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(alpha_data__.data(), K);
      {
        std::vector<local_scalar_t__> alpha_flat__;
        current_statement__ = 73;
        alpha_flat__ = context__.vals_r("alpha");
        current_statement__ = 73;
        pos__ = 1;
        current_statement__ = 73;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 73;
          stan::model::assign(alpha, alpha_flat__[(pos__ - 1)],
            "assigning variable alpha", stan::model::index_uni(sym1__));
          current_statement__ = 73;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 74;
      stan::math::validate_non_negative_index("eta", "J", J);
      current_statement__ = 75;
      stan::math::validate_non_negative_index("eta", "R", R);
      current_statement__ = 76;
      context__.validate_dims("data initialization", "eta", "double",
        std::vector<size_t>{static_cast<size_t>(J), static_cast<size_t>(R)});
      eta_data__ = Eigen::Matrix<double,-1,-1>::Constant(J, R,
                     std::numeric_limits<double>::quiet_NaN());
      new (&eta) Eigen::Map<Eigen::Matrix<double,-1,-1>>(eta_data__.data(),
        J, R);
      {
        std::vector<local_scalar_t__> eta_flat__;
        current_statement__ = 76;
        eta_flat__ = context__.vals_r("eta");
        current_statement__ = 76;
        pos__ = 1;
        current_statement__ = 76;
        for (int sym1__ = 1; sym1__ <= R; ++sym1__) {
          current_statement__ = 76;
          for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
            current_statement__ = 76;
            stan::model::assign(eta, eta_flat__[(pos__ - 1)],
              "assigning variable eta", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 76;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 77;
      stan::math::validate_non_negative_index("mu0", "K", K);
      current_statement__ = 78;
      stan::math::validate_non_negative_index("mu0", "q", q);
      current_statement__ = 79;
      context__.validate_dims("data initialization", "mu0", "double",
        std::vector<size_t>{static_cast<size_t>(K), static_cast<size_t>(q)});
      mu0 = std::vector<Eigen::Matrix<double,-1,1>>(K,
              Eigen::Matrix<double,-1,1>::Constant(q,
                std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> mu0_flat__;
        current_statement__ = 79;
        mu0_flat__ = context__.vals_r("mu0");
        current_statement__ = 79;
        pos__ = 1;
        current_statement__ = 79;
        for (int sym1__ = 1; sym1__ <= q; ++sym1__) {
          current_statement__ = 79;
          for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
            current_statement__ = 79;
            stan::model::assign(mu0, mu0_flat__[(pos__ - 1)],
              "assigning variable mu0", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 79;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 80;
      stan::math::validate_non_negative_index("Sig0", "K", K);
      current_statement__ = 81;
      stan::math::validate_non_negative_index("Sig0", "q", q);
      current_statement__ = 81;
      stan::math::validate_non_negative_index("Sig0", "q", q);
      current_statement__ = 82;
      context__.validate_dims("data initialization", "Sig0", "double",
        std::vector<size_t>{static_cast<size_t>(K), static_cast<size_t>(q),
          static_cast<size_t>(q)});
      Sig0 = std::vector<Eigen::Matrix<double,-1,-1>>(K,
               Eigen::Matrix<double,-1,-1>::Constant(q, q,
                 std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> Sig0_flat__;
        current_statement__ = 82;
        Sig0_flat__ = context__.vals_r("Sig0");
        current_statement__ = 82;
        pos__ = 1;
        current_statement__ = 82;
        for (int sym1__ = 1; sym1__ <= q; ++sym1__) {
          current_statement__ = 82;
          for (int sym2__ = 1; sym2__ <= q; ++sym2__) {
            current_statement__ = 82;
            for (int sym3__ = 1; sym3__ <= K; ++sym3__) {
              current_statement__ = 82;
              stan::model::assign(Sig0, Sig0_flat__[(pos__ - 1)],
                "assigning variable Sig0", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 82;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 82;
      stan::math::check_cov_matrix(function__, "Sig0", Sig0);
      current_statement__ = 83;
      stan::math::validate_positive_index("pi", "K", K);
      current_statement__ = 84;
      stan::math::validate_non_negative_index("theta", "J", J);
      current_statement__ = 85;
      stan::math::validate_non_negative_index("theta", "K", K);
      current_statement__ = 86;
      stan::math::validate_positive_index("theta", "R", R);
      current_statement__ = 87;
      stan::math::validate_non_negative_index("xi", "K", K);
      current_statement__ = 88;
      stan::math::validate_non_negative_index("xi", "q", q);
      current_statement__ = 89;
      stan::math::validate_non_negative_index("theta_prod", "J", J);
      current_statement__ = 90;
      stan::math::validate_non_negative_index("theta_prod", "R", R);
      current_statement__ = 91;
      stan::math::validate_non_negative_index("xi_prod", "q", q);
      current_statement__ = 92;
      stan::math::validate_non_negative_index("pred_class_probs", "n", n);
      current_statement__ = 93;
      stan::math::validate_non_negative_index("pred_class_probs", "K", K);
      current_statement__ = 94;
      stan::math::validate_non_negative_index("pred_class", "n", n);
      current_statement__ = 95;
      stan::math::validate_non_negative_index("log_cond_c", "n", n);
      current_statement__ = 96;
      stan::math::validate_non_negative_index("log_cond_c", "K", K);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (K - 1) + (J * K * (R - 1)) + (K * q);
  }
  inline std::string model_name() const final {
    return "model_SWOLCA_main";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_SWOLCA_main_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> pi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 1;
      pi = in__.template read_constrain_simplex<
             Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__, K);
      std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>> theta =
        std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>(J,
          std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(K,
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(R, DUMMY_VAR__)));
      current_statement__ = 2;
      theta = in__.template read_constrain_simplex<
                std::vector<
                  std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>,
                jacobian__>(lp__, J, K, R);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> xi =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(K,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(q, DUMMY_VAR__));
      current_statement__ = 3;
      xi = in__.template read<
             std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>(K, q);
      Eigen::Matrix<local_scalar_t__,-1,-1> theta_prod =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(J, R, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> xi_prod =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(q, DUMMY_VAR__);
      current_statement__ = 13;
      for (int j = 1; j <= J; ++j) {
        current_statement__ = 11;
        for (int r = 1; r <= R; ++r) {
          current_statement__ = 9;
          stan::model::assign(theta_prod,
            stan::math::prod(
              stan::model::rvalue(theta, "theta", stan::model::index_uni(j),
                stan::model::index_omni(), stan::model::index_uni(r))),
            "assigning variable theta_prod", stan::model::index_uni(j),
            stan::model::index_uni(r));
        }
      }
      current_statement__ = 16;
      for (int v = 1; v <= q; ++v) {
        current_statement__ = 14;
        stan::model::assign(xi_prod,
          stan::math::prod(
            stan::model::rvalue(xi, "xi", stan::model::index_omni(),
              stan::model::index_uni(v))), "assigning variable xi_prod",
          stan::model::index_uni(v));
      }
      {
        current_statement__ = 27;
        stan::math::validate_non_negative_index("log_cond_c", "n", n);
        current_statement__ = 28;
        stan::math::validate_non_negative_index("log_cond_c", "K", K);
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> log_cond_c =
          std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(n,
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__));
        current_statement__ = 30;
        stan::math::validate_non_negative_index("Vi_xi", "n", n);
        Eigen::Matrix<local_scalar_t__,-1,1> Vi_xi =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
        current_statement__ = 32;
        lp_accum__.add(stan::math::dirichlet_lpdf<propto__>(pi, alpha));
        current_statement__ = 37;
        for (int j = 1; j <= J; ++j) {
          current_statement__ = 35;
          for (int k = 1; k <= K; ++k) {
            current_statement__ = 33;
            lp_accum__.add(stan::math::dirichlet_lpdf<propto__>(
                             stan::model::rvalue(theta, "theta",
                               stan::model::index_uni(j),
                               stan::model::index_uni(k)),
                             stan::model::rvalue(eta, "eta",
                               stan::model::index_uni(j),
                               stan::model::index_omni())));
          }
        }
        current_statement__ = 40;
        for (int k = 1; k <= K; ++k) {
          current_statement__ = 38;
          lp_accum__.add(stan::math::multi_normal_lpdf<propto__>(
                           stan::model::rvalue(xi, "xi",
                             stan::model::index_uni(k)),
                           stan::model::rvalue(mu0, "mu0",
                             stan::model::index_uni(k)),
                           stan::model::rvalue(Sig0, "Sig0",
                             stan::model::index_uni(k))));
        }
        current_statement__ = 56;
        for (int i = 1; i <= n; ++i) {
          current_statement__ = 53;
          for (int k = 1; k <= K; ++k) {
            current_statement__ = 41;
            stan::model::assign(Vi_xi,
              stan::math::multiply(
                stan::math::to_row_vector(
                  stan::model::rvalue(V, "V", stan::model::index_uni(i),
                    stan::model::index_omni())),
                stan::model::rvalue(xi, "xi", stan::model::index_uni(k))),
              "assigning variable Vi_xi", stan::model::index_uni(i));
            current_statement__ = 44;
            if (stan::math::logical_lt(
                  stan::model::rvalue(Vi_xi, "Vi_xi",
                    stan::model::index_uni(i)), -8)) {
              current_statement__ = 42;
              stan::model::assign(Vi_xi, -8, "assigning variable Vi_xi",
                stan::model::index_uni(i));
            }
            current_statement__ = 47;
            if (stan::math::logical_gt(
                  stan::model::rvalue(Vi_xi, "Vi_xi",
                    stan::model::index_uni(i)), 8)) {
              current_statement__ = 45;
              stan::model::assign(Vi_xi, 9, "assigning variable Vi_xi",
                stan::model::index_uni(i));
            }
            current_statement__ = 48;
            stan::model::assign(log_cond_c,
              (stan::math::log(
                 stan::model::rvalue(pi, "pi", stan::model::index_uni(k))) +
              stan::math::bernoulli_lpmf<false>(
                stan::model::rvalue(y, "y", stan::model::index_uni(i)),
                stan::math::Phi(
                  stan::model::rvalue(Vi_xi, "Vi_xi",
                    stan::model::index_uni(i))))),
              "assigning variable log_cond_c", stan::model::index_uni(i),
              stan::model::index_uni(k));
            current_statement__ = 51;
            for (int j = 1; j <= J; ++j) {
              current_statement__ = 49;
              stan::model::assign(log_cond_c,
                (stan::model::rvalue(log_cond_c, "log_cond_c",
                   stan::model::index_uni(i), stan::model::index_uni(k)) +
                stan::math::categorical_lpmf<false>(
                  stan::model::rvalue(X, "X", stan::model::index_uni(i),
                    stan::model::index_uni(j)),
                  stan::model::rvalue(theta, "theta",
                    stan::model::index_uni(j), stan::model::index_uni(k),
                    stan::model::index_omni()))),
                "assigning variable log_cond_c", stan::model::index_uni(i),
                stan::model::index_uni(k));
            }
          }
          current_statement__ = 54;
          lp_accum__.add((stan::model::rvalue(weights, "weights",
                            stan::model::index_uni(i)) *
            stan::math::log_sum_exp(
              stan::model::rvalue(log_cond_c, "log_cond_c",
                stan::model::index_uni(i)))));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_SWOLCA_main_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> pi =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      pi = in__.template read_constrain_simplex<
             Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__, K);
      std::vector<std::vector<Eigen::Matrix<double,-1,1>>> theta =
        std::vector<std::vector<Eigen::Matrix<double,-1,1>>>(J,
          std::vector<Eigen::Matrix<double,-1,1>>(K,
            Eigen::Matrix<double,-1,1>::Constant(R,
              std::numeric_limits<double>::quiet_NaN())));
      current_statement__ = 2;
      theta = in__.template read_constrain_simplex<
                std::vector<
                  std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>,
                jacobian__>(lp__, J, K, R);
      std::vector<Eigen::Matrix<double,-1,1>> xi =
        std::vector<Eigen::Matrix<double,-1,1>>(K,
          Eigen::Matrix<double,-1,1>::Constant(q,
            std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 3;
      xi = in__.template read<
             std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>(K, q);
      Eigen::Matrix<double,-1,-1> theta_prod =
        Eigen::Matrix<double,-1,-1>::Constant(J, R,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> xi_prod =
        Eigen::Matrix<double,-1,1>::Constant(q,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(pi);
      for (int sym1__ = 1; sym1__ <= R; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= J; ++sym3__) {
            out__.write(theta[(sym3__ - 1)][(sym2__ - 1)][(sym1__ - 1)]);
          }
        }
      }
      for (int sym1__ = 1; sym1__ <= q; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          out__.write(xi[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 13;
      for (int j = 1; j <= J; ++j) {
        current_statement__ = 11;
        for (int r = 1; r <= R; ++r) {
          current_statement__ = 9;
          stan::model::assign(theta_prod,
            stan::math::prod(
              stan::model::rvalue(theta, "theta", stan::model::index_uni(j),
                stan::model::index_omni(), stan::model::index_uni(r))),
            "assigning variable theta_prod", stan::model::index_uni(j),
            stan::model::index_uni(r));
        }
      }
      current_statement__ = 16;
      for (int v = 1; v <= q; ++v) {
        current_statement__ = 14;
        stan::model::assign(xi_prod,
          stan::math::prod(
            stan::model::rvalue(xi, "xi", stan::model::index_omni(),
              stan::model::index_uni(v))), "assigning variable xi_prod",
          stan::model::index_uni(v));
      }
      if (emit_transformed_parameters__) {
        out__.write(theta_prod);
        out__.write(xi_prod);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      std::vector<Eigen::Matrix<double,-1,1>> pred_class_probs =
        std::vector<Eigen::Matrix<double,-1,1>>(n,
          Eigen::Matrix<double,-1,1>::Constant(K,
            std::numeric_limits<double>::quiet_NaN()));
      std::vector<int> pred_class =
        std::vector<int>(n, std::numeric_limits<int>::min());
      std::vector<Eigen::Matrix<double,-1,1>> log_cond_c =
        std::vector<Eigen::Matrix<double,-1,1>>(n,
          Eigen::Matrix<double,-1,1>::Constant(K,
            std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 26;
      for (int i = 1; i <= n; ++i) {
        current_statement__ = 22;
        for (int k = 1; k <= K; ++k) {
          current_statement__ = 17;
          stan::model::assign(log_cond_c,
            (stan::math::log(
               stan::model::rvalue(pi, "pi", stan::model::index_uni(k))) +
            stan::math::bernoulli_lpmf<false>(
              stan::model::rvalue(y, "y", stan::model::index_uni(i)),
              stan::math::Phi(
                stan::math::multiply(
                  stan::math::to_row_vector(
                    stan::model::rvalue(V, "V", stan::model::index_uni(i),
                      stan::model::index_omni())),
                  stan::model::rvalue(xi, "xi", stan::model::index_uni(k)))))),
            "assigning variable log_cond_c", stan::model::index_uni(i),
            stan::model::index_uni(k));
          current_statement__ = 20;
          for (int j = 1; j <= J; ++j) {
            current_statement__ = 18;
            stan::model::assign(log_cond_c,
              (stan::model::rvalue(log_cond_c, "log_cond_c",
                 stan::model::index_uni(i), stan::model::index_uni(k)) +
              stan::math::categorical_lpmf<false>(
                stan::model::rvalue(X, "X", stan::model::index_uni(i),
                  stan::model::index_uni(j)),
                stan::model::rvalue(theta, "theta",
                  stan::model::index_uni(j), stan::model::index_uni(k),
                  stan::model::index_omni()))),
              "assigning variable log_cond_c", stan::model::index_uni(i),
              stan::model::index_uni(k));
          }
        }
        current_statement__ = 23;
        stan::model::assign(pred_class_probs,
          stan::math::exp(
            stan::math::subtract(
              stan::model::rvalue(log_cond_c, "log_cond_c",
                stan::model::index_uni(i), stan::model::index_omni()),
              stan::math::log_sum_exp(
                stan::model::rvalue(log_cond_c, "log_cond_c",
                  stan::model::index_uni(i))))),
          "assigning variable pred_class_probs", stan::model::index_uni(i),
          stan::model::index_omni());
        current_statement__ = 24;
        stan::model::assign(pred_class,
          stan::math::categorical_rng(
            stan::model::rvalue(pred_class_probs, "pred_class_probs",
              stan::model::index_uni(i), stan::model::index_omni()),
            base_rng__), "assigning variable pred_class",
          stan::model::index_uni(i));
      }
      current_statement__ = 6;
      stan::math::check_simplex(function__, "pred_class_probs",
        pred_class_probs);
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "pred_class",
        pred_class, 1);
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          out__.write(pred_class_probs[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      out__.write(pred_class);
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          out__.write(log_cond_c[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> pi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(pi,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable pi");
      out__.write_free_simplex(pi);
      std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>> theta =
        std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>(J,
          std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(K,
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(R, DUMMY_VAR__)));
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= R; ++sym1__) {
        current_statement__ = 2;
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          current_statement__ = 2;
          for (int sym3__ = 1; sym3__ <= J; ++sym3__) {
            current_statement__ = 2;
            stan::model::assign(theta, in__.read<local_scalar_t__>(),
              "assigning variable theta", stan::model::index_uni(sym3__),
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
          }
        }
      }
      out__.write_free_simplex(theta);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> xi =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(K,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(q, DUMMY_VAR__));
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= q; ++sym1__) {
        current_statement__ = 3;
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          current_statement__ = 3;
          stan::model::assign(xi, in__.read<local_scalar_t__>(),
            "assigning variable xi", stan::model::index_uni(sym2__),
            stan::model::index_uni(sym1__));
        }
      }
      out__.write(xi);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "pi", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "theta", "double",
        std::vector<size_t>{static_cast<size_t>(J), static_cast<size_t>(K),
          static_cast<size_t>(R)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "xi", "double",
        std::vector<size_t>{static_cast<size_t>(K), static_cast<size_t>(q)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> pi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> pi_flat__;
        current_statement__ = 1;
        pi_flat__ = context__.vals_r("pi");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(pi, pi_flat__[(pos__ - 1)],
            "assigning variable pi", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_simplex(pi);
      std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>> theta =
        std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>(J,
          std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(K,
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(R, DUMMY_VAR__)));
      {
        std::vector<local_scalar_t__> theta_flat__;
        current_statement__ = 2;
        theta_flat__ = context__.vals_r("theta");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= R; ++sym1__) {
          current_statement__ = 2;
          for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
            current_statement__ = 2;
            for (int sym3__ = 1; sym3__ <= J; ++sym3__) {
              current_statement__ = 2;
              stan::model::assign(theta, theta_flat__[(pos__ - 1)],
                "assigning variable theta", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 2;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      out__.write_free_simplex(theta);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> xi =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(K,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(q, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> xi_flat__;
        current_statement__ = 3;
        xi_flat__ = context__.vals_r("xi");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= q; ++sym1__) {
          current_statement__ = 3;
          for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
            current_statement__ = 3;
            stan::model::assign(xi, xi_flat__[(pos__ - 1)],
              "assigning variable xi", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 3;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(xi);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"pi", "theta", "xi"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"theta_prod", "xi_prod"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string>
        temp{"pred_class_probs", "pred_class", "log_cond_c"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(K)},
                std::vector<size_t>{static_cast<size_t>(J),
                  static_cast<size_t>(K), static_cast<size_t>(R)},
                std::vector<size_t>{static_cast<size_t>(K),
                  static_cast<size_t>(q)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(J),
               static_cast<size_t>(R)},
             std::vector<size_t>{static_cast<size_t>(q)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(n),
               static_cast<size_t>(K)},
             std::vector<size_t>{static_cast<size_t>(n)},
             std::vector<size_t>{static_cast<size_t>(n),
               static_cast<size_t>(K)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "pi" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= R; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
        for (int sym3__ = 1; sym3__ <= J; ++sym3__) {
          param_names__.emplace_back(std::string() + "theta" + '.' +
            std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
            std::to_string(sym1__));
        }
      }
    }
    for (int sym1__ = 1; sym1__ <= q; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
        param_names__.emplace_back(std::string() + "xi" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= R; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
          param_names__.emplace_back(std::string() + "theta_prod" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= q; ++sym1__) {
        param_names__.emplace_back(std::string() + "xi_prod" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          param_names__.emplace_back(std::string() + "pred_class_probs" + '.'
            + std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        param_names__.emplace_back(std::string() + "pred_class" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          param_names__.emplace_back(std::string() + "log_cond_c" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
      param_names__.emplace_back(std::string() + "pi" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= (R - 1); ++sym1__) {
      for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
        for (int sym3__ = 1; sym3__ <= J; ++sym3__) {
          param_names__.emplace_back(std::string() + "theta" + '.' +
            std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
            std::to_string(sym1__));
        }
      }
    }
    for (int sym1__ = 1; sym1__ <= q; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
        param_names__.emplace_back(std::string() + "xi" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= R; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
          param_names__.emplace_back(std::string() + "theta_prod" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= q; ++sym1__) {
        param_names__.emplace_back(std::string() + "xi_prod" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          param_names__.emplace_back(std::string() + "pred_class_probs" + '.'
            + std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        param_names__.emplace_back(std::string() + "pred_class" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
          param_names__.emplace_back(std::string() + "log_cond_c" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"pi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(J) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(K) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(R) + "}}},\"block\":\"parameters\"},{\"name\":\"xi\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(K) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(q) + "}},\"block\":\"parameters\"},{\"name\":\"theta_prod\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(J) + ",\"cols\":" + std::to_string(R) + "},\"block\":\"transformed_parameters\"},{\"name\":\"xi_prod\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(q) + "},\"block\":\"transformed_parameters\"},{\"name\":\"pred_class_probs\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "}},\"block\":\"generated_quantities\"},{\"name\":\"pred_class\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"int\"}},\"block\":\"generated_quantities\"},{\"name\":\"log_cond_c\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "}},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"pi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string((K -1)) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(J) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(K) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string((R -1)) + "}}},\"block\":\"parameters\"},{\"name\":\"xi\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(K) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(q) + "}},\"block\":\"parameters\"},{\"name\":\"theta_prod\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(J) + ",\"cols\":" + std::to_string(R) + "},\"block\":\"transformed_parameters\"},{\"name\":\"xi_prod\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(q) + "},\"block\":\"transformed_parameters\"},{\"name\":\"pred_class_probs\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string((K -1)) + "}},\"block\":\"generated_quantities\"},{\"name\":\"pred_class\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"int\"}},\"block\":\"generated_quantities\"},{\"name\":\"log_cond_c\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "}},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((K + ((J * K) * R)) + (K * q));
    const size_t num_transformed = emit_transformed_parameters * (((J * R) +
      q));
    const size_t num_gen_quantities = emit_generated_quantities * ((((n * K)
      + n) + (n * K)));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((K + ((J * K) * R)) + (K * q));
    const size_t num_transformed = emit_transformed_parameters * (((J * R) +
      q));
    const size_t num_gen_quantities = emit_generated_quantities * ((((n * K)
      + n) + (n * K)));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_SWOLCA_main_namespace::model_SWOLCA_main;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_SWOLCA_main_namespace::profiles__;
}
#endif
#endif
