# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rdirichlet_cpp <- function(alpha) {
    .Call(`_baysc_rdirichlet_cpp`, alpha)
}

rcat_cpp <- function(probs) {
    .Call(`_baysc_rcat_cpp`, probs)
}

mvrnorm_cpp <- function(n, mu, sigma) {
    .Call(`_baysc_mvrnorm_cpp`, n, mu, sigma)
}

mvrnorm_cpp2 <- function(n, mu, sigma) {
    .Call(`_baysc_mvrnorm_cpp2`, n, mu, sigma)
}

mvrnorm_cpp3 <- function(n, mu, sigma) {
    .Call(`_baysc_mvrnorm_cpp3`, n, mu, sigma)
}

rtruncnorm_cpp <- function(n, a, b, mean, sd) {
    .Call(`_baysc_rtruncnorm_cpp`, n, a, b, mean, sd)
}

logSumExp_cpp <- function(x) {
    .Call(`_baysc_logSumExp_cpp`, x)
}

update_pi <- function(pi, w_all, c_all, K, alpha) {
    invisible(.Call(`_baysc_update_pi`, pi, w_all, c_all, K, alpha))
}

update_c <- function(c_all, n, K, p, theta, x_mat, pi, z_all, V, xi, y_all) {
    invisible(.Call(`_baysc_update_c`, c_all, n, K, p, theta, x_mat, pi, z_all, V, xi, y_all))
}

update_c_WOLCA <- function(c_all, n, K, p, theta, x_mat, pi) {
    invisible(.Call(`_baysc_update_c_WOLCA`, c_all, n, K, p, theta, x_mat, pi))
}

update_theta <- function(theta, p, K, d, eta, w_all, c_all, x_mat) {
    invisible(.Call(`_baysc_update_theta`, theta, p, K, d, eta, w_all, c_all, x_mat))
}

update_xi <- function(xi, n, K, w_all, c_all, z_all, V, mu0, Sig0) {
    .Call(`_baysc_update_xi`, xi, n, K, w_all, c_all, z_all, V, mu0, Sig0)
}

update_z <- function(z_all, n, V, xi, c_all, y_all) {
    .Call(`_baysc_update_z`, z_all, n, V, xi, c_all, y_all)
}

update_loglik <- function(loglik, n, p, c_all, theta, x_mat, pi, z_all, V, xi, y_all) {
    invisible(.Call(`_baysc_update_loglik`, loglik, n, p, c_all, theta, x_mat, pi, z_all, V, xi, y_all))
}

update_c_test <- function(c_all, n, K, p, theta, x_mat, pi, z_all, V, xi, y_all) {
    invisible(.Call(`_baysc_update_c_test`, c_all, n, K, p, theta, x_mat, pi, z_all, V, xi, y_all))
}

