# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Draw from a Dirichlet distribution
#' 
#' @param alpha Vector of positive concentration parameters. Length determines
#' the number of dimensions for the Dirichlet distribution.
#' @return Vector result of a single draw from the specified Dirichlet distribution
#' @importFrom stats rgamma
#' @keywords internal
rdirichlet_cpp <- function(alpha) {
    .Call(`_baysc_rdirichlet_cpp`, alpha)
}

#' Draw from a Categorical distribution
#' 
#' @param probs Row vector of category event probabilities. Length determines
#' the number of categories for the Categorical distribution.
#' @return Integer specifying the category (1-based indexing) of a single draw 
#' from the specified Categorical distribution
#' @importFrom stats rmultinom
#' @keywords internal
rcat_cpp <- function(probs) {
    .Call(`_baysc_rcat_cpp`, probs)
}

#' Draw from a Multivariate Normal distribution
#' 
#' @param n Number of draws
#' @param mu Vector of means with length equal to number of dimensions
#' @param sigma Positive-definite symmetric covariance matrix 
#' @return Matrix result of draws from the specified Multivariate Normal 
#' distribution, with rows corresponding to draws and columns corresponding to 
#' dimensions.
#' @keywords internal
mvrnorm_cpp <- function(n, mu, sigma) {
    .Call(`_baysc_mvrnorm_cpp`, n, mu, sigma)
}

#' Draw from a truncated Normal distribution
#'
#' @param n Number of draws
#' @param a Lower bound
#' @param b Upper bound
#' @param mean Mean
#' @param sd Standard deviation
#' @return Result of a single draw from the specified truncated Normal distribution
#' @importFrom truncnorm rtruncnorm
#' @keywords internal
rtruncnorm_cpp <- function(n, a, b, mean, sd) {
    .Call(`_baysc_rtruncnorm_cpp`, n, a, b, mean, sd)
}

#' Apply log-sum-exp trick 
#' 
#' @description
#' `logSumExp_cpp` computes the logarithm of the sum of exponentials, adapted from 
#' https://github.com/helske/seqHMM/blob/main/src/logSumExp.cpp.
#'
#' @param x Row vector of input values
#' @return Result of computing the logarithm of the sum of exponentials of the
#' input values.
#' @keywords internal
logSumExp_cpp <- function(x) {
    .Call(`_baysc_logSumExp_cpp`, x)
}

#' Update pi
#' 
#' `update_pi` updates the vector parameter of class membership probabilities, pi, by 
#' drawing from its posterior.
#' 
#' @inheritParams run_MCMC_Rcpp
#' @param pi Vector parameter of class membership probabilities. Kx1
#' 
#' @return Updated `pi` vector after drawing from its posterior distribution
#' @keywords internal
update_pi <- function(pi, w_all, c_all, K, alpha) {
    invisible(.Call(`_baysc_update_pi`, pi, w_all, c_all, K, alpha))
}

#' Update c
#' 
#' `update_c` updates the vector of individual class assignments, c, by drawing 
#' from a Categorical distribution with updated category event probabilities.
#' 
#' @inheritParams run_MCMC_Rcpp
#' @param pi Vector parameter of class membership probabilities. Kx1
#' @param theta Array parameter of item level probabilities. JxKxR
#' @param z_all Vector of latent variables in the probit model. nx1
#' @param xi Matrix parameter xi for probit regression coefficients. Kxq
#' 
#' @return Updated `c_all` vector after drawing from a Categorical distribution
#' with updated category event probabilities.
#' @keywords internal
update_c <- function(c_all, n, K, J, theta, x_mat, pi, z_all, V, xi, y_all) {
    invisible(.Call(`_baysc_update_c`, c_all, n, K, J, theta, x_mat, pi, z_all, V, xi, y_all))
}

#' Update c for WOLCA
#' 
#' Updates the vector of individual class assignments, c, for the unsupervised
#' model.
#' 
#' @inheritParams update_c
#' 
#' @return Updated `c_all` vector after drawing from a Categorical distribution
#' with updated category event probabilities for the unsupervised model.
#' @keywords internal
update_c_wolca <- function(c_all, n, K, J, theta, x_mat, pi) {
    invisible(.Call(`_baysc_update_c_wolca`, c_all, n, K, J, theta, x_mat, pi))
}

#' Update theta
#' 
#' `update_theta` updates the array of item level probabilities, theta, by
#' drawing from its posterior.
#' 
#' @inheritParams update_c
#' 
#' @return Updated `theta` array after drawing from its posterior distribution.
#' @keywords internal
update_theta <- function(theta, J, K, R, eta, w_all, c_all, x_mat) {
    invisible(.Call(`_baysc_update_theta`, theta, J, K, R, eta, w_all, c_all, x_mat))
}

#' Update xi
#' 
#' `update_xi` updates the matrix of outcome regression coefficients, xi, by
#' drawing from its posterior.
#' 
#' @inheritParams update_c
#' 
#' @return Updated `xi` matrix after drawing from its posterior distribution.
#' @keywords internal
update_xi <- function(xi, n, K, w_all, c_all, z_all, V, mu0, Sig0) {
    .Call(`_baysc_update_xi`, xi, n, K, w_all, c_all, z_all, V, mu0, Sig0)
}

#' Update z
#' 
#' `update_z` updates the vector of latent probit variables, z, by drawing 
#' from a Truncated Normal distribution with updated mean.
#' 
#' @inheritParams update_c
#' 
#' @return Updated `z_all` vector after drawing from a Truncated Normal 
#' distribution with updated mean.
#' @keywords internal
update_z <- function(z_all, n, V, xi, c_all, y_all) {
    .Call(`_baysc_update_z`, z_all, n, V, xi, c_all, y_all)
}

#' Update individual log-likelihood
#' 
#' `update_loglik` updates the vector of individual log-likelihoods using the
#' updated parameters and latent variables.
#' 
#' @inheritParams update_c
#' 
#' @return Updated `loglik` vector after using the updated parameters and 
#' latent variables.
#' @keywords internal
update_loglik <- function(loglik, n, J, c_all, theta, x_mat, pi, z_all, V, xi, y_all) {
    invisible(.Call(`_baysc_update_loglik`, loglik, n, J, c_all, theta, x_mat, pi, z_all, V, xi, y_all))
}

